# Advanced.default.yml contains the default values and is overwritten regularly.
# Rename it to Advanced.yml if you want to change values.

# IMPORTANT:
#   This file is for advanced tweaks. You are expected to be familiar with YAML and its pitfalls if you decide to edit it.
#   Check the log for warnings related to this file and DO NOT open issues asking for help on how to format this file.

Tames:
  TeleportFollowPositioning:
    MinDistXZ: 2
    MaxDistXZ: 4
    MinOffsetY: 0
    MaxOffsetY: 1
    HalfArcXZ: 45
  TeleportFollow:
    Asksvin: true
    Boar: true
    Hen: true
    Lox: true
    Skeleton_Friendly: true
    Wolf: true
  TakeIntoDungeon:
    Asksvin: true
    Boar: true
    Hen: true
    Lox: true
    Skeleton_Friendly: true
    Wolf: true
HostileSummons:
  FollowSummoners:
    MoveInterval: 4
    MaxDistance: 20
Containers:
  ChestSignOffsets:
    piece_chest_wood:
      Left: 0.8
      Right: 0.8
      Front: 0.4
      Back: 0.4
      Top: 0.8
    piece_chest:
      Left: 0.85
      Right: 0.85
      Front: 0.5
      Back: 0.5
      Top: 1.1
    piece_chest_blackmetal:
      Left: 0.95
      Right: 0.95
      Front: 0.7
      Back: 0.7
      Top: 0.95
    piece_chest_barrel:
      Left: 0.4
      Right: 0.4
      Front: 0.4
      Back: 0.4
      Top: 0.9
    incinerator:
      Left: .nan
      Right: .nan
      Front: 0.1
      Back: .nan
      Top: 3
